### ISSUE TITLE
Unable to start stack. Errors of the other container starting but unable to join.

### ISSUE THREAD

**Issue by thisisnotfez** [N1ghtm4r3x/mullvad-docker#3]
Error via Portainer: 
```
failed to deploy a stack: Network mullvad-test_default Creating Network mullvad-test_default Created Container vpn Creating Container vpn Created Container qbittorrent1 Creating Container qbittorrent1 Created Container vpn Starting Container vpn Started Container qbittorrent1 Starting Error response from daemon: Container 783e7f8b79cef21b861ad56792a552c2600ae614d87bba60abf54dc0cef236a1 is restarting, wait until the container is running
```

Compose file:
```
version: '3.8'
services:
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent
        container_name: qbittorrent1
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Phoenix
            - WEBUI_PORT=1010
        volumes:
            - ./qbit/config:/config
            - ./qbit/downloads:/downloads
        restart: unless-stopped
        network_mode: service:vpn
        depends_on:
            - vpn
    vpn:
        image: n1ghtm4r3x/mullvad-docker
        container_name: vpn
        hostname: vpn # Found this setting from other people regarding similar use cases of VPN in containers
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - TZ=America/Phoenix # Set timezone
            - ACCOUNT=foobar
            - COUNTRY=us # Choose the country you would like to use, Default is se (Sweden)
            - LOCAL_SUBNET=192.168.2.0/24 # Add your local subnet
        volumes:
            - ./wg:/etc/wireguard # Set this to where you would like to save the wireguard config files
            - /lib/modules:/lib/modules:ro
        ports:
            - 1010:1010 # Example for linuxserver qbittorrent
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
            - net.ipv6.conf.all.disable_ipv6=1
        restart: unless-stopped
        ulimits: # Found this setting from other people regarding similar use cases of VPN in containers
            memlock:
                soft: -1
                hard: -1
```
All my persistent volume binds are otherwise default from the example as I'm only testing it to first make sure it's going to work.

Other mentions are to put in a healthcheck, but couldn't figure out which container gets it. I recently found https://docs.docker.com/compose/startup-order/ and will try to integrate one of the solutions mentioned.

However, as it stands, I am not the only person who is having trouble with this.
